apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-aks-app-deployment
  namespace: bheg-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-aks-app
  template:
    metadata:
      labels:
        app: flask-aks-app
    spec:
      containers:
      - name: flask-aks-app
        image: hegdebhavya9/testimage:latest  
        ports:
        - containerPort: 5000
